### ISSUE TITLE
JS Interview Questions

### ISSUE THREAD

**Issue by ashishnandal-daffodil** [sudheerj/javascript-interview-questions#152]

**Comment by riggulate** [comment]
Tried to call you but your company has done nothing but harrass me and used
my friends and family to threaten me so you got until 0900 to get your shit
off my phone and leave me alone forever because you fukin with the wrong
one bet that. Got screen shot of it all you know the scert stuff royal
Ratch aka royal majestic you ant the only who knows some shit
